- name: oddsbender-scrapers-barstool-football
  kind: deployment
  up: 1
  down: 0
- name: oddsbender-scrapers-betmgm-basketball
  kind: deployment
  up: 1
  down: 0
- name: oddsbender-scrapers-betmgm-football
  kind: deployment
  up: 1
  down: 0
- name: oddsbender-scrapers-caesars-basketball
  kind: deployment
  up: 1
  down: 0
- name: oddsbender-scrapers-caesars-football
  kind: deployment
  up: 1
  down: 0
- name: oddsbender-scrapers-draftkings-basketball
  kind: deployment
  up: 1
  down: 0
- name: oddsbender-scrapers-draftkings-football
  kind: deployment
  up: 1
  down: 0
- name: oddsbender-scrapers-fanduel-basketball
  kind: deployment
  up: 1
  down: 0
- name: oddsbender-scrapers-fanduel-football
  kind: deployment
  up: 1
  down: 0
- name: oddsbender-scrapers-sugarhouse-basketball
  kind: deployment
  up: 1
  down: 0
- name: oddsbender-scrapers-sugarhouse-football
  kind: deployment
  up: 1
  down: 0
- name: oddsbender-scrapers-betmgm-basketball-prop
  kind: deployment
  up: 1
  down: 0
- name: oddsbender-scrapers-betmgm-football-prop
  kind: deployment
  up: 1
  down: 0
- name: oddsbender-scrapers-caesars-basketball-prop
  kind: deployment
  up: 1
  down: 0
- name: oddsbender-scrapers-caesars-football-prop
  kind: deployment
  up: 1
  down: 0
- name: oddsbender-scrapers-draftkings-basketball-prop
  kind: deployment
  up: 1
  down: 0
- name: oddsbender-scrapers-draftkings-football-prop
  kind: deployment
  up: 1
  down: 0
- name: oddsbender-scrapers-fanduel-basketball-prop
  kind: deployment
  up: 1
  down: 0
- name: oddsbender-scrapers-fanduel-football-prop
  kind: deployment
  up: 1
  down: 0
- name: oddsbender-scrapers-sugarhouse-basketball-prop
  kind: deployment
  up: 1
  down: 0
- name: oddsbender-scrapers-sugarhouse-football-prop
  kind: deployment
  up: 1
  down: 0
- name: oddsbender-scrapers-master-scheduler
  kind: deployment
  core: true
  up: 1
  down: 0
- name: oddsbender-scrapers-data-loader
  kind: deployment
  core: true
  up: 1
  down: 0
- name: oddsbender-back-end-compare
  kind: deployment
  core: true
  up: 1
  down: 0
- name: oddsbender-scrapers-redis-master
  kind: statefulset
  core: true
  up: 1
  down: 0
- name: oddsbender-scrapers-redis-replicas
  kind: statefulset
  core: true
  up: 3
  down: 0
- name: oddsbender-scrapers-rabbitmq
  kind: statefulset
  core: true
  up: 0
  down: 0
